### ISSUE TITLE
RuntimeError: can't create new thread at interpreter shutdown - V0.5.0

### ISSUE THREAD

**Issue by Kolaposki** [joaomdmoura/crewAI#225]
I updated the crewAI to 0.5.0 yesterday and started getting these errors below. Note that the agent execution and tasks work just fine. Python itself is just throwing the error unnecessarily.

```Python 3.12```

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1431, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/user1/Desktop/GPTTrial/env/lib/python3.12/site-packages/crewai/utilities/rpm_controller.py", line 57, in _reset_request_count
    self._timer.start()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
```

I added max_iter=10 and max_rpm=20 to the agent but didn't stop the error.
I wasn't getting this error on my console before. The v0.5.0 caused this, and I stand to be corrected.

**Comment by joaomdmoura** [comment]
Good catch, found a bug in the RPM code, fixed and will cut a new version tonight, I'll close the issue for now but let me know once you update crewai if the problem still exists
