### ISSUE TITLE
Getting Started code doesn't work

### ISSUE THREAD

**Issue by CohleM** [joaomdmoura/crewAI#264]
I just installed crewai using pip and ran the code in the **Getting started** section. The throws the following error.

```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 2
      1 import os
----> 2 from crewai import Agent, Task, Crew, Process
      4 os.environ["OPENAI_API_KEY"] = "YOUR_API_KEY"
      6 # You can choose to use a local model through Ollama for example. See ./docs/how-to/llm-connections.md for more information.
      7 # from langchain_community.llms import Ollama
      8 # ollama_llm = Ollama(model="openhermes")
      9 
     10 # Install duckduckgo-search for this example:
     11 # !pip install -U duckduckgo-search

File ~/anaconda3/envs/crewai/lib/python3.9/site-packages/crewai/__init__.py:1
----> 1 from crewai.agent import Agent
      2 from crewai.crew import Crew
      3 from crewai.process import Process

File ~/anaconda3/envs/crewai/lib/python3.9/site-packages/crewai/agent.py:22
     10 from pydantic import (
     11     UUID4,
     12     BaseModel,
   (...)
     18     model_validator,
     19 )
     20 from pydantic_core import PydanticCustomError
---> 22 from crewai.agents import (
     23     CacheHandler,
     24     CrewAgentExecutor,
     25     CrewAgentOutputParser,
     26     ToolsHandler,
     27 )
     28 from crewai.utilities import I18N, Logger, Prompts, RPMController
     31 class Agent(BaseModel):

File ~/anaconda3/envs/crewai/lib/python3.9/site-packages/crewai/agents/__init__.py:2
      1 from .cache.cache_handler import CacheHandler
----> 2 from .executor import CrewAgentExecutor
      3 from .output_parser import CrewAgentOutputParser
      4 from .tools_handler import ToolsHandler

File ~/anaconda3/envs/crewai/lib/python3.9/site-packages/crewai/agents/executor.py:16
     14 from crewai.agents.cache.cache_hit import CacheHit
     15 from crewai.tools.cache_tools import CacheTools
---> 16 from crewai.utilities import I18N
     19 class CrewAgentExecutor(AgentExecutor):
     20     i18n: I18N = I18N()

File ~/anaconda3/envs/crewai/lib/python3.9/site-packages/crewai/utilities/__init__.py:4
      2 from .logger import Logger
      3 from .prompts import Prompts
----> 4 from .rpm_controller import RPMController

File ~/anaconda3/envs/crewai/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py:10
      5 from pydantic import BaseModel, ConfigDict, Field, PrivateAttr, model_validator
      7 from crewai.utilities.logger import Logger
---> 10 class RPMController(BaseModel):
     11     model_config = ConfigDict(arbitrary_types_allowed=True)
     12     max_rpm: Union[int, None] = Field(default=None)

File ~/anaconda3/envs/crewai/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py:15, in RPMController()
     13 logger: Logger = Field(default=None)
     14 _current_rpm: int = PrivateAttr(default=0)
---> 15 _timer: threading.Timer | None = PrivateAttr(default=None)
     16 _lock: threading.Lock = PrivateAttr(default=None)
     18 @model_validator(mode="after")
     19 def reset_counter(self):

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

I'm currently using python 3.9

**Comment by joaomdmoura** [comment]
Hey there, the issue is the python version :)
python version needs to be at least 3.10.0

--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em qui., 22 de fev. de 2024 às 02:47, CohleM ***@***.***>
escreveu:

**Comment by andersoncavalcantedasilva** [comment]
Hi @joaomdmoura,
I'm facing the same problem but my Python version is 3.12.3.

```
/usr/bin/python3 /Users/anderson/projects/agents/gettingStarted.py
anderson@Laptop agents % /usr/bin/python3 /Users/anderson/projects/agents/gettingStarted.py
Traceback (most recent call last):
  File "/Users/anderson/projects/agents/gettingStarted.py", line 9, in <module>
    from crewai import Agent
  File "/Users/anderson/Library/Python/3.9/lib/python/site-packages/crewai/__init__.py", line 1, in <module>
    from crewai.agent import Agent
  File "/Users/anderson/Library/Python/3.9/lib/python/site-packages/crewai/agent.py", line 22, in <module>
    from crewai.agents import (
  File "/Users/anderson/Library/Python/3.9/lib/python/site-packages/crewai/agents/__init__.py", line 2, in <module>
    from .executor import CrewAgentExecutor
  File "/Users/anderson/Library/Python/3.9/lib/python/site-packages/crewai/agents/executor.py", line 16, in <module>
    from crewai.utilities import I18N
  File "/Users/anderson/Library/Python/3.9/lib/python/site-packages/crewai/utilities/__init__.py", line 4, in <module>
    from .rpm_controller import RPMController
  File "/Users/anderson/Library/Python/3.9/lib/python/site-packages/crewai/utilities/rpm_controller.py", line 10, in <module>
    class RPMController(BaseModel):
  File "/Users/anderson/Library/Python/3.9/lib/python/site-packages/crewai/utilities/rpm_controller.py", line 15, in RPMController
    _timer: threading.Timer | None = PrivateAttr(default=None)
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
anderson@Laptop agents % python3 --version
Python 3.12.3
```

**Comment by mesmalif** [comment]
Thanks @joaomdmoura but crewai assistant recommends 3.8 or above

<img width="822" alt="image" src="https://github.com/joaomdmoura/crewAI/assets/34637500/23f65ee2-cd2c-469f-ac27-6164b9593399">

**Comment by pisces76** [comment]
same issue. Suggest update CrewAI doc. @joaomdmoura
