### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

### ISSUE THREAD

**Issue by okoliechykwuka** [joaomdmoura/crewAI#39]
I installed crewAI via pip on WSL and tried importing the Agents via `from crewai import Agent`

I am getting the below error.

/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'GraalVM JSSE'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/crewai/__init__.py", line 1, in <module>
    from crewai.agent import Agent
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/crewai/agent.py", line 3, in <module>
    from langchain.agents import AgentExecutor
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langchain/agents/__init__.py", line 36, in <module>
    from langchain.agents.agent import (
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langchain/agents/agent.py", line 26, in <module>
    from langchain_core.language_models import BaseLanguageModel
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langchain_core/language_models/__init__.py", line 8, in <module>
    from langchain_core.language_models.chat_models import BaseChatModel, SimpleChatModel
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 20, in <module>
    from langchain_core.callbacks import (
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langchain_core/callbacks/__init__.py", line 13, in <module>
    from langchain_core.callbacks.manager import (
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langchain_core/callbacks/manager.py", line 27, in <module>
    from langsmith.run_helpers import get_run_tree_context
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langsmith/__init__.py", line 10, in <module>
    from langsmith.client import Client
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langsmith/client.py", line 43, in <module>
    from langsmith.evaluation import evaluator as ls_evaluator
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langsmith/evaluation/__init__.py", line 4, in <module>
    from langsmith.evaluation.string_evaluator import StringEvaluator
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/langsmith/evaluation/string_evaluator.py", line 3, in <module>
    from pydantic import BaseModel
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/pydantic/__init__.py", line 372, in __getattr__
    module = import_module(module_name, package=package)
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/pydantic/main.py", line 11, in <module>
    import pydantic_core
  File "/home/chukypedro15/miniconda3/envs/rfp_env/lib/jvm/languages/python/lib/python3.10/site-packages/pydantic_core/__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

**Comment by okoliechykwuka** [comment]
@greysonlalonde I switched back to conda and everything works fine now. Thanks
