### ISSUE TITLE
Did not find openai_api_key

### ISSUE THREAD

**Issue by vanetreg** [joaomdmoura/CrewAI#5]
Using .env file and a key named "OPENAI_API_KEY" in it ( with valid value),
I still got:
```
Traceback (most recent call last):
  File "D:\Projects\AI_testing\CrewAI\sample_app.py", line 5, in <module>
    researcher = Agent(
                 ^^^^^^
  File "D:\Projects\AI_testing\CrewAI\CrewAI-venv\Lib\site-packages\crewai\agent.py", line 49, in __init__
    super().__init__(**data)
  File "D:\Projects\AI_testing\CrewAI\CrewAI-venv\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Agent
__root__ -> __root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
```
error.

**Comment by joaomdmoura** [comment]
Hey @vanetreg I'll try it out locally to double check but I don't think crewai automatically loads it. Are you using `python-dotenv`? And if so are you loading the file?
```python
from dotenv import load_dotenv
load_result = load_dotenv(override=True)
```

**Comment by vanetreg** [comment]
I haven't loaded dotenv, my bad... 
I'm not a pro dev though :)
