### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 186-192: character maps to <undefined>

### ISSUE THREAD

**Issue by vmsaif** [joaomdmoura/crewAI#713]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\ats_pass_ai\src\ats_pass_ai\main.py", line 142, in run
    crew.kickoff()
  File "G:\ats_pass_ai\.venv\Lib\site-packages\crewai\crew.py", line 264, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ats_pass_ai\.venv\Lib\site-packages\crewai\crew.py", line 313, in _run_sequential_process
    self._file_handler.log(agent=role, task=task_output, status="completed")        
  File "G:\ats_pass_ai\.venv\Lib\site-packages\crewai\utilities\fileHandler.py", line 20, in log
    file.write(message + "\n")
  File "C:\Users\vmsai\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

**Comment by e4stwood** [comment]
How did you fix this? I'm getting the same in a different location
